services:
  youtube-downloader-api:
    image: registry.svc.lan/backend/youtube-downloader-api:latest
    container_name: youtube-downloader-api
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
